Diabetes.MVC/Models/Insulin/CreateInsulinViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Diabetes.Domain.Enums;
using Diabetes.MVC.Attributes.Validation;

namespace Diabetes.MVC.Models.Insulin
{
    public class CreateInsulinViewModel
    { 
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Значение (ед.)")]
        [Double(1,100, ErrorMessage = "Допустимы числа от 1 до 100, с двумя знаками после запятой")]
        public string Value {
            get => _value?.Replace(',','.');
            init => _value = value;
        }

        private readonly string _value = "";
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Дата измерения")]
        public string MeasuringDate { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Время измерения")]
        public string MeasuringTime { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Тип инсулина")]
        public InsulinType InsulinType { get; set; }
        
        [DisplayName("Заметка")]
        [StringLength(200, ErrorMessage = "Длина должна быть не более 200 символов")]
        public string Comment { get; set; }
        
        public string ReturnUrl { get; set; }
    }
}

Diabetes.MVC/Models/Insulin/EditInsulinViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Diabetes.Domain.Enums;
using Diabetes.MVC.Attributes.Validation;

namespace Diabetes.MVC.Models.Insulin
{
    public class EditInsulinViewModel
    {
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Guid записи")]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Значение (ед.)")]
        [Double(1,100, ErrorMessage = "Допустимы числа от 1 до 100, с двумя знаками после запятой")]
        public string Value {
            get => _value?.Replace(',','.');
            init => _value = value;
        }

        private readonly string _value = "";
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Дата измерения")]
        public string MeasuringDate { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Время измерения")]
        public string MeasuringTime { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Тип инсулина")]
        public InsulinType InsulinType { get; set; }
        
        [DisplayName("Заметка")]
        [StringLength(200, ErrorMessage = "Длина должна быть не более 200 символов")]
        public string Comment { get; set; }

        public string ReturnUrl { get; set; }
    }
}

Diabetes.MVC/Controllers/InsulinController.cs
using Diabetes.Application.NoteInsulin.Commands.CreateNoteInsulin;
using Diabetes.MVC.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Globalization;
using System.Threading.Tasks;
using Diabetes.Application.NoteInsulin.Commands.GetNoteInsulin;
using Diabetes.Domain;
using Diabetes.MVC.Extensions;
using Diabetes.MVC.Models.Insulin;
using Microsoft.AspNetCore.Authorization;

namespace Diabetes.MVC.Controllers
{
    [Route("[controller]/[action]")]
    public class InsulinController:Controller
    {
        private readonly IMediator _mediator;

        public InsulinController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddInsulin(string returnUrl)
        {
            var viewModel = new CreateInsulinViewModel {ReturnUrl = returnUrl};
            return View(viewModel);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddInsulin(CreateInsulinViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var command = new CreateNoteInsulinCommand
            {
                UserId = User.GetId(),
                InsulinValue = double.Parse(viewModel.Value, NumberStyles.Float, CultureInfo.InvariantCulture),
                MeasuringDateTime = DateTime.ParseExact($"{viewModel.MeasuringDate} {viewModel.MeasuringTime}", 
                    "yyyy-MM-dd HH:mm", System.Globalization.CultureInfo.InvariantCulture),
                InsulinType = viewModel.InsulinType,
                Comment = viewModel.Comment
            };

            await _mediator.Send(command);

            return RedirectToAction("Index", "Home");
        }
        
        [HttpGet("{id:guid}")]
        [Authorize]
        public async Task<IActionResult> EditInsulin(Guid id)
        {
            var getInsulinCommand = new GetNoteInsulinCommand
            {
                Id = id
            };

            var model = await _mediator.Send(getInsulinCommand);
            
            if (model == null)
                return RedirectToAction("Index", "Home");
            
            var viewModel = new EditInsulinViewModel
            {
                Id = model.Id,
                Value = model.Value.ToString(), 
                MeasuringTime = model.MeasuringDateTime.ToString("HH:mm"),
                MeasuringDate = model.MeasuringDateTime.ToString("yyyy-MM-dd"),
                Comment = model.Comment,
                InsulinType = model.InsulinType
            };
            
            return View(viewModel);
        }

        [HttpPost("{id:guid}")]
        [Authorize]
        public async Task<IActionResult> EditInsulin(EditInsulinViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var command = new EditNoteInsulinCommand 
            {
                UserId = User.GetId(),
                Id = viewModel.Id,
                InsulinValue = double.Parse(viewModel.Value, NumberStyles.Float, CultureInfo.InvariantCulture),
                MeasuringDateTime = DateTime.ParseExact($"{viewModel.MeasuringDate} {viewModel.MeasuringTime}",
                        "yyyy-MM-dd HH:mm", System.Globalization.CultureInfo.InvariantCulture),
                InsulinType = viewModel.InsulinType,
                Comment = viewModel.Comment

            };

            await _mediator.Send(command);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet("{id:guid}")]
        [Authorize]
        public async Task<IActionResult> DeleteInsulin(Guid id)
        {
            if(id == Guid.Empty) 
                return NotFound();
            
            var command = new DeleteNoteInsulinCommand 
            {
                UserId = User.GetId(), 
                Id = id,
            };
            
            await _mediator.Send(command);

            return RedirectToAction("Index", "Home");
        }
    }
}

Diabetes.MVC/Views/Insulin/AddInsulin.cshtml
@using Diabetes.MVC.Models.Components
@using Diabetes.Domain.Normalized.Enums
@using Diabetes.Domain.Enums
@model Diabetes.MVC.Models.Insulin.CreateInsulinViewModel

@{
    ViewData["Title"] = "Инсулин";
}

@await Component.InvokeAsync("AddSelector", new{ model = new AddSelectorModel(false, true, false) })

<form asp-controller="Insulin" asp-action="AddInsulin" role="form" method="post">
    <div class="mb-3">
        <label asp-for="Value" class="form-label"></label>
        <input asp-for="Value" class="form-control" value="0">
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="MeasuringDate" class="form-label"></label>
        <input asp-for="MeasuringDate" type="date" class="form-control" id="datePicker">
        <span asp-validation-for="MeasuringDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="MeasuringTime" class="form-label"></label>
        <input asp-for="MeasuringTime" type="time" class="form-control" id="timePicker">
        <span asp-validation-for="MeasuringTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Comment" class="form-label"></label><span><small class="text-muted "> (необязательно)</small></span>
        <textarea asp-for="Comment" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="InsulinType" class="form-label"></label>
        <select asp-for="InsulinType" asp-items="Html.GetEnumSelectList<InsulinType>()"></select>
        <span asp-validation-for="InsulinType" class="text-danger"></span>
    </div>
    <div class="col-lg-6 col-sm-8 pull-right">
        <a class="btn btn-default" asp-controller="Home" asp-action="Index">Отмена</a>
        <button class="btn btn-success" id="btn" type="submit">Подтвердить</button>
    </div>
</form>

<script>
var now = new Date()
var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);
var date = now.getFullYear()+"-"+(month)+"-"+(day) ;
var time = now.toLocaleTimeString().substr(0,5)

$('#datePicker').val(date);
$('#timePicker').val(time);
</script>

Diabetes.MVC/Views/Insulin/EditInsulin.cshtml
@using Diabetes.Domain.Enums
@model Diabetes.MVC.Models.Insulin.EditInsulinViewModel

@{
    ViewData["Title"] = "Инсулин";
}

<form asp-controller="Insulin" asp-action="EditInsulin" method="post">
    <div class="mb-3">
        <input asp-for="Id" class="form-control d-none">
    </div>
    <div class="mb-3">
        <label asp-for="Value" class="form-label"></label>
        <input asp-for="Value" class="form-control">
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="MeasuringDate" class="form-label"></label>
        <input asp-for="MeasuringDate" type="date" class="form-control" id="datePicker">
        <span asp-validation-for="MeasuringDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="MeasuringTime" class="form-label"></label>
        <input asp-for="MeasuringTime" type="time" class="form-control" id="timePicker">
        <span asp-validation-for="MeasuringTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Comment" class="form-label"></label><span><small class="text-muted "> (необязательно)</small></span>
        <textarea asp-for="Comment" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="InsulinType" class="form-label"></label>
        <select asp-for="InsulinType" asp-items="Html.GetEnumSelectList<InsulinType>()"></select>
        <span asp-validation-for="InsulinType" class="text-danger"></span>
    </div>
    <div class="col-lg-6 col-sm-8 pull-right">
        <a class="btn btn-default" asp-controller="Home" asp-action="Index" onchange="setSelection()">Отмена</a>
        <button class="btn btn-success" id="btn" type="submit">Подтвердить</button>
    </div>
</form>