Diabetes.MVC/Controllers/CarbohydrateController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Diabetes.Application.Carbohydrate.Commands.AddCarbohydrate;
using Diabetes.Application.Carbohydrate.Commands.DeleteCarbohydrate;
using Diabetes.Application.Carbohydrate.Commands.EditCarbohydrate;
using Diabetes.Application.Carbohydrate.Commands.GetCarbohydrateById;
using Diabetes.Application.Food.Commands.GetFoodById;
using Diabetes.Domain;
using Diabetes.MVC.Extensions;
using Diabetes.MVC.Models.FoodForNote;
using Diabetes.MVC.Models.Meal;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Diabetes.MVC.Controllers
{
    [Route("[controller]/[action]")]
    public class CarbohydrateController:Controller
    {
        private IMediator _mediator;

        public CarbohydrateController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Authorize]
        [HttpGet("{newCard:bool?}")]
        public IActionResult Add(bool? newCard)
        {
            if(newCard is true)
                HttpContext.Clear(HttpContextExtensions.AddKey);
            
            var vm = HttpContext.GetMeal(HttpContextExtensions.AddKey);

            return View(vm);
        }
        
        [Authorize]
        [HttpPost("{newCard:bool?}")]
        public async Task<IActionResult> Add(MealViewModel vm)
        {
            vm.Foods = HttpContext.GetMeal(HttpContextExtensions.AddKey).Foods;
            
            if (!ModelState.IsValid)
            {
                return View(vm);   
            }

            var carbohydrateNoteId = Guid.NewGuid();
            var command = new AddCarbohydrateCommand
            {
                MealId = carbohydrateNoteId,
                UserId = User.GetId(),
                Value = double.Parse(vm.Value, NumberStyles.Float, CultureInfo.InvariantCulture),
                Comment = vm.Comment,
                CreatingDateTime = DateTime.ParseExact($"{vm.CreatingDate} " + $"{vm.CreatingTime}", "yyyy-MM-dd HH:mm",
                    CultureInfo.InvariantCulture),
                FoodPortions = vm.Foods.Select(f => new FoodPortion
                    {
                        FoodId = f.FoodId, 
                        CarbohydrateNoteId = carbohydrateNoteId,
                        MassInGr = f.MassInGramNum
                    }
                ).ToList()
            };

            foreach (var foodPortion in command.FoodPortions)
            {
                foodPortion.Food = await _mediator.Send(new GetFoodByIdCommand {Id = foodPortion.FoodId});
            }

            await _mediator.Send(command);
            
            HttpContext.Clear(HttpContextExtensions.AddKey);

            return RedirectToAction("Index", "Home");
        }
        
        [Authorize]
        [HttpGet("{id:guid?}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            MealViewModel vm;
            
            if (id == null)
            {
                vm = HttpContext.GetMeal(HttpContextExtensions.EditKey);
            }
            else
            {
                var note = await _mediator.Send(new GetCarbohydrateByIdCommand {Id = id.Value, UserId = User.GetId()});
                
                if (note == null)
                    return RedirectToAction("Index", "Home");

                vm = new MealViewModel
                {
                    Id = id.Value,
                    Value = note.Value.ToString(),
                    Comment = note.Comment,
                    CreatingDate = note.MeasuringDateTime.ToString("yyyy-MM-dd"),
                    CreatingTime = note.MeasuringDateTime.ToString("HH:mm"),
                    Foods = note.Portions.Select(f =>
                    {
                        f.Food.Portions = new List<FoodPortion>();
                        f.Food.CarbohydrateNotes = new List<CarbohydrateNote>();
                        return new FoodForNoteViewModel
                        {
                            Food = f.Food,
                            FoodId = f.FoodId,
                            MassInGram = f.MassInGr.ToString(CultureInfo.InvariantCulture)
                        };
                    }).ToList()
                };
                HttpContext.AddMeal(vm, HttpContextExtensions.EditKey);
            }
            
            return View(vm);
        }
        
        [Authorize]
        [HttpPost("{id:guid?}")]
        public async Task<IActionResult> Edit(MealViewModel vm)
        {
            vm.Foods = HttpContext.GetMeal(HttpContextExtensions.EditKey).Foods;
            
            if (!ModelState.IsValid)
            {
                return View(vm);   
            }
            
            var command = new EditCarbohydrateCommand
            {
                Id = vm.Id,
                UserId = User.GetId(),
                Value = double.Parse(vm.Value, NumberStyles.Float, CultureInfo.InvariantCulture),
                Comment = vm.Comment,
                CreatingDateTime = DateTime.ParseExact($"{vm.CreatingDate} " + $"{vm.CreatingTime}", "yyyy-MM-dd HH:mm",
                    CultureInfo.InvariantCulture),
                FoodPortions = vm.Foods.Select(f => new FoodPortion
                    {
                        FoodId = f.FoodId, 
                        CarbohydrateNoteId = vm.Id,
                        MassInGr = f.MassInGramNum
                    }
                ).ToList()
            };

            foreach (var foodPortion in command.FoodPortions)
            {
                foodPortion.Food = await _mediator.Send(new GetFoodByIdCommand {Id = foodPortion.FoodId});
            }

            await _mediator.Send(command);
            
            HttpContext.Clear(HttpContextExtensions.EditKey);

            return RedirectToAction("Index", "Home");
        }
        
        
        [HttpGet("{id:guid}")]
        [Authorize]
        public async Task<IActionResult> Delete(Guid id)
        { 
            if(id == Guid.Empty) 
                return NotFound();
            
            var command = new DeleteCarbohydrateCommand 
            {
                Id = id,
                UserId = User.GetId()
            };

            await _mediator.Send(command);

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddFoodToListAdding(MealViewModel vm)
        {
            HttpContext.RememberData(vm, HttpContextExtensions.AddKey);
            return RedirectToAction("Index", "FoodForNote", new {id = vm.Id});
        }
        
        [Authorize]
        [HttpPost]
        public IActionResult AddFoodToListEditing(MealViewModel vm)
        {
            HttpContext.RememberData(vm, HttpContextExtensions.EditKey);
            return RedirectToAction("Index", "FoodForNoteEditing", new {id = vm.Id});
        }
    }
}

Diabetes.MVC/Views/Carbohydrate/Add.cshtml
@using Diabetes.MVC.Models.Components
@model Diabetes.MVC.Models.Meal.MealViewModel

@{
    ViewData["Title"] = "Приём пищи";
}

@await Component.InvokeAsync("AddSelector", new{ model = new AddSelectorModel(true, false, false) })

<form role="form" method="post">

    <div class="d-flex justify-content-between">
        <h4>Список продуктов</h4>
        <button class="btn btn-primary" type="submit" asp-controller="Carbohydrate" asp-action="AddFoodToListAdding">Добавить продукт</button>
    </div>

    @await Component.InvokeAsync("FoodListInMeal", new{ model = new FoodForNoteListViewModel(Model.Foods)})

    <hr>
    
    <div class="row mt-5"></div>

    <div class="mb-3">
        <label asp-for="Value" class="form-label"></label>
        <input oninput="onInput()" id="value"  asp-for="Value" class="form-control">
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div>
            <span>Углеводов в продуктах: </span><span id="food-result"></span>
        </div>
        <div>
            <span>Дополнительных углеводов: </span><span id="extra-result"></span>
        </div>
        <div>
            <span>Итого углеводов: </span><span id="result"></span>
        </div>
    </div>    
    <div class="mb-3">
        <label asp-for="CreatingDate" class="form-label"></label>
        <input asp-for="CreatingDate" type="date" class="form-control" id="datePicker">
        <span asp-validation-for="CreatingDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CreatingTime" class="form-label"></label>
        <input asp-for="CreatingTime" type="time" class="form-control" id="timePicker">
        <span asp-validation-for="CreatingTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Comment" class="form-label"></label><span><small class="text-muted "> (необязательно)</small></span>
        <textarea asp-for="Comment" class="form-control"></textarea>
    </div>
    <div class="col-lg-6 col-sm-8 pull-right">
        <a class="btn btn-default" asp-controller="Home" asp-action="Index">Отмена</a>
        <button class="btn btn-success" id="btn" type="submit" asp-controller="Carbohydrate" asp-action="Add">Подтвердить</button>
    </div>
</form>

<script>
var now = new Date()
var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);
var date = now.getFullYear()+"-"+(month)+"-"+(day) ;
var time = now.toLocaleTimeString().substr(0,5)

if ($('#datePicker').val() === '')
    $('#datePicker').val(date);

if ($('#timePicker').val() === '')
    $('#timePicker').val(time);
</script>

<script>
function onInput(){
    let value = Number($("#value").val().replace(',','.'));
    if (!isNaN(value) && value >= 0){
        $("#food-result").text(Number(@Model.FoodsValue).toFixed(2))
        $("#result").text((value + @Model.FoodsValue).toFixed(2));
        $("#extra-result").text((value).toFixed(2));
    }
    else{
        $("#result").text("Некорректное значение");
        $("#extra-result").text("Некорректное значение");
    }
}

onInput();
</script>

Diabetes.MVC/Views/Carbohydrate/AddMeal.cshtml
@using Diabetes.MVC.Models.Components
@model Diabetes.MVC.Models.Meal.MealViewModel

@{
    ViewData["Title"] = "Приём пищи";
}

@await Component.InvokeAsync("AddSelector", new{ model = new AddSelectorModel(true, false, false) })

<form role="form" method="post">

    <div class="d-flex justify-content-between">
        <h4>Список продуктов</h4>
        <a class="btn btn-outline-primary" asp-controller="FoodForNote" asp-action="Index">Добавить продукт</a>
    </div>

    @await Component.InvokeAsync("FoodListInMeal", new{ model = new FoodForNoteListViewModel(Model.Foods)})

    <hr>
    
    <div class="d-flex justify-content-end">
        <button class="btn btn-outline-secondary" asp-controller="FoodForNote" asp-action="RememberData">Запомнить данные</button>
    </div>
    
    <div class="mb-3">
        <label asp-for="Value" class="form-label"></label>
        <input oninput="onInput()" id="value"  asp-for="Value" class="form-control">
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <span>Итого углеводов: </span>
        <span id="result"></span>
    </div>    
    <div class="mb-3">
        <label asp-for="CreatingDate" class="form-label"></label>
        <input asp-for="CreatingDate" type="date" class="form-control" id="datePicker">
        <span asp-validation-for="CreatingDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CreatingTime" class="form-label"></label>
        <input asp-for="CreatingTime" type="time" class="form-control" id="timePicker">
        <span asp-validation-for="CreatingTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Comment" class="form-label"></label><span><small class="text-muted "> (необязательно)</small></span>
        <textarea asp-for="Comment" class="form-control"></textarea>
    </div>
    <div class="col-lg-6 col-sm-8 pull-right">
        <a class="btn btn-default" asp-controller="Home" asp-action="Index">Отмена</a>
        <button class="btn btn-success" id="btn" type="submit" asp-controller="Carbohydrate" asp-action="AddMeal">Подтвердить</button>
    </div>
</form>

<script>
var now = new Date()
var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);
var date = now.getFullYear()+"-"+(month)+"-"+(day) ;
var time = now.toLocaleTimeString().substr(0,5)

if ($('#datePicker').val() === '')
    $('#datePicker').val(date);

if ($('#timePicker').val() === '')
    $('#timePicker').val(time);
</script>

<script>
function onInput(){
    let value = Number($("#value").val().replace(',','.'));
    if (!isNaN(value) && value >= 0){
        $("#result").text((value + @Model.FoodsValue).toFixed(2));
    }
    else{
        $("#result").text("Некорректное значение");
    }
}

onInput();
</script>

Diabetes.MVC/Views/Carbohydrate/Edit.cshtml
@using Diabetes.MVC.Models.Components
@model Diabetes.MVC.Models.Meal.MealViewModel

@{
    ViewData["Title"] = "Изменение приёма пищи";
}

<form role="form" method="post">

    <div class="d-flex justify-content-between">
        <h4>Список продуктов</h4>
        <button class="btn btn-primary" type="submit" asp-controller="Carbohydrate" asp-action="AddFoodToListEditing">Добавить продукт</button>
    </div>

    @await Component.InvokeAsync("FoodListInMealEditing", new{ model = new FoodForNoteListViewModel(Model.Foods)})

    <hr>
    
    <div class="row mt-5"></div>

    <div class="mb-3">
        <input asp-for="Id" class="form-control d-none">
    </div>
    
    <div class="mb-3">
        <label asp-for="Value" class="form-label"></label>
        <input oninput="onInput()" id="value" asp-for="Value" class="form-control">
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div>
            <span>Углеводов в продуктах: </span><span id="food-result"></span>
        </div>
        <div>
            <span>Дополнительных углеводов: </span><span id="extra-result"></span>
        </div>
        <div>
            <span>Итого углеводов: </span><span id="result"></span>
        </div>
    </div>    
    <div class="mb-3">
        <label asp-for="CreatingDate" class="form-label"></label>
        <input asp-for="CreatingDate" type="date" class="form-control" id="datePicker">
        <span asp-validation-for="CreatingDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CreatingTime" class="form-label"></label>
        <input asp-for="CreatingTime" type="time" class="form-control" id="timePicker">
        <span asp-validation-for="CreatingTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Comment" class="form-label"></label><span><small class="text-muted "> (необязательно)</small></span>
        <textarea asp-for="Comment" class="form-control"></textarea>
    </div>
    <div class="col-lg-6 col-sm-8 pull-right">
        <a class="btn btn-default" asp-controller="FoodForNoteEditing" asp-action="Cancel">Отмена</a>
        <button class="btn btn-success" id="btn" type="submit" asp-controller="Carbohydrate" asp-action="Edit">Подтвердить</button>
    </div>
</form>

<script>
function onInput(){
    let value = Number($("#value").val().replace(',','.'));
    if (!isNaN(value) && value >= 0){
        $("#food-result").text(Number(@Model.FoodsValue).toFixed(2))
        $("#result").text((value + @Model.FoodsValue).toFixed(2));
        $("#extra-result").text((value).toFixed(2));
    }
    else{
        $("#result").text("Некорректное значение");
        $("#extra-result").text("Некорректное значение");
    }
}

onInput();
</script>