Diabetes.MVC/Models/Statistics/StatisticsGlucoseViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Diabetes.MVC.Models
{
    public class GlucoseGraphics
    {
        public string Categorical { get; set; }
        public double Value { get; set; }
        public double? NormalValueBeforeEating { get; set; }
        public double? NormalValueAfterEating { get; set; }
    }

    public class StatisticsGlucoseViewModel
    {
        [DisplayName("Дополнительный параметр")]
        public string GlucoseAdditional { get; set; }

        [DisplayName("Временной промежуток")]
        public string GlucoseTimePeriod { get; set; }
        [DisplayName("Единица измерения")]
        public string GlucoseUnit { get; set; }

        [DisplayName("Произвольная дата")]
        public string CustomDate { get; set; }

        public List<double> Values;
        public List<string> Categorical;
        public List<double?> NormalValuesBeforeEating;
        public List<double?> NormalValuesAfterEating;

        public List<GlucoseGraphics> GetData() =>
            Categorical.Zip(Values, (a, b) => new Tuple<string, double>(a, b))
            .Zip(NormalValuesBeforeEating, (a, b) => new Tuple<string, double, double?>(a.Item1, a.Item2, b))
            .Zip(NormalValuesAfterEating, (a, b) => new GlucoseGraphics() 
            { Categorical = a.Item1, Value = a.Item2, NormalValueBeforeEating = a.Item3, NormalValueAfterEating = b})
            .ToList();

        public bool HasNormalBeforeEating { get; set; }
        public bool HasNormalAfterEating { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Diabetes.MVC/Controllers/StatisticsGlucoseController.cs
using Microsoft.AspNetCore.Mvc;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Diabetes.MVC.Models;
using Diabetes.Application.Statistics.Commands;
using System.Linq;
using Diabetes.Persistence;
using Diabetes.Domain.Enums;
using Microsoft.AspNetCore.Identity;
using System;
using System.Threading.Tasks;
using System.Globalization;
using Diabetes.MVC.Extensions;
using Diabetes.Domain.Normalized.Enums.Units;

namespace Diabetes.MVC.Controllers
{
    public class StatisticsGlucoseController: Controller
    {
        private readonly IMediator _mediator;
        private readonly UserManager<Account> _userManager;
        public StatisticsGlucoseController(IMediator mediator, UserManager<Account> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }

        [Authorize]
        public async Task <IActionResult> Index (string returnUrl)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var viewModel = new StatisticsGlucoseViewModel
            {
                ReturnUrl = returnUrl,
                HasNormalBeforeEating = user.NormalGlucoseBeforeEating.HasValue,
                HasNormalAfterEating = user.NormalGlucoseAfterEating.HasValue,
                GlucoseUnit = user.GlucoseUnits switch
                {
                    GlucoseUnits.MmolPerLiter => "0",
                    GlucoseUnits.MgramPerDeciliter => "1"
                }
            };

            Func<MeasuringTimeType, bool> MTFilter = a => true;

            Func<DateTime, bool> DFilter = a => (DateTime.Now.Date - a.Date).Days < 7 && (DateTime.Now.Date - a.Date).Days >= 0;

            var command = new GetGlucoseCommand
            {
                MeasuringTimeFilter = MTFilter,
                DateFilter = DFilter
            };

            var itemsList = await _mediator.Send(command);
            itemsList = itemsList.Where(a => a.UserId == User.GetId()).ToList();

            viewModel.Categorical = itemsList.Select(a => a.MeasuringDateTime.ToString("dd.MM.yyyy HH:mm")).ToList();
            viewModel.Values = itemsList.Select(a => Math.Round(a.Value.Value, 2)).ToList();
            viewModel.NormalValuesBeforeEating = itemsList.Select(a => user.NormalGlucoseBeforeEating).ToList();
            viewModel.NormalValuesAfterEating = itemsList.Select(a => user.NormalGlucoseAfterEating).ToList();
            viewModel.HasNormalBeforeEating = user.NormalGlucoseBeforeEating.HasValue;
            viewModel.HasNormalAfterEating = user.NormalGlucoseAfterEating.HasValue;
            if (viewModel.GlucoseUnit == "1")
            {
                viewModel.Values = viewModel.Values.Select(a => Math.Round(18 * a, 2)).ToList();
                viewModel.NormalValuesBeforeEating = viewModel.NormalValuesBeforeEating.Select(a => a.HasValue ? Math.Round(18 * a.Value, 2) : a).ToList();
                viewModel.NormalValuesAfterEating = viewModel.NormalValuesAfterEating.Select(a => a.HasValue ? Math.Round(18 * a.Value, 2) : a).ToList();
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task <IActionResult> GlucoseGraphics(StatisticsGlucoseViewModel viewModel)
        {
            if (viewModel.CustomDate == null) viewModel.CustomDate = DateTime.Now.ToString("yyyy-MM-dd");
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            Func<MeasuringTimeType, bool> MTFilter = viewModel.GlucoseAdditional switch
            {
                "1" => a => a == MeasuringTimeType.BeforeEating,
                "2" => a => a == MeasuringTimeType.AfterEating,
                _ => a => true,
            };

            Func<DateTime, bool> DFilter = viewModel.GlucoseTimePeriod switch
            {
                "1" => a => (DateTime.Now.Year - a.Year) * 12 +
                DateTime.Now.Month - a.Month +
                (DateTime.Now.Day >= a.Day ? 0 : -1) == 0,
                "2" => a => a.Date == DateTime.Now.Date,
                "3" => a => a.Date == DateTime.ParseExact(viewModel.CustomDate, "yyyy-MM-dd",
                CultureInfo.InvariantCulture).Date,
                "4" => a => true,
                _ => a => (DateTime.Now.Date - a.Date).Days < 7 && (DateTime.Now.Date - a.Date).Days >= 0,
            };

            var command = new GetGlucoseCommand
            {
                MeasuringTimeFilter = MTFilter,
                DateFilter = DFilter
            };

            var itemsList = await _mediator.Send(command);
            itemsList = itemsList.Where(a => a.UserId == User.GetId()).ToList();

            viewModel.Categorical = itemsList.Select(a => a.MeasuringDateTime.ToString("dd.MM.yyyy HH:mm")).ToList();
            viewModel.Values = itemsList.Select(a => Math.Round(a.Value.Value, 2)).ToList();
            viewModel.NormalValuesBeforeEating = itemsList.Select(a => user.NormalGlucoseBeforeEating).ToList();
            viewModel.NormalValuesAfterEating = itemsList.Select(a => user.NormalGlucoseAfterEating).ToList();
            viewModel.HasNormalBeforeEating = user.NormalGlucoseBeforeEating.HasValue;
            viewModel.HasNormalAfterEating = user.NormalGlucoseAfterEating.HasValue;
            if (viewModel.GlucoseUnit == "1")
            {
                viewModel.Values = viewModel.Values.Select(a => Math.Round(18 * a, 2)).ToList();
                viewModel.NormalValuesBeforeEating = viewModel.NormalValuesBeforeEating.Select(a => a.HasValue ? Math.Round(18 * a.Value, 2) : a).ToList();
                viewModel.NormalValuesAfterEating = viewModel.NormalValuesAfterEating.Select(a => a.HasValue ? Math.Round(18 * a.Value, 2) : a).ToList();
            }
            return View(viewModel);
        }
    }
}

Diabetes.MVC/Controllers/StatisticsInsulinController.cs
using Microsoft.AspNetCore.Mvc;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Diabetes.MVC.Models;
using Diabetes.Application.Statistics.Commands;
using System.Linq;
using System.Globalization;
using Diabetes.Domain.Enums;
using System;
using System.Threading.Tasks;
using Diabetes.MVC.Extensions;

namespace Diabetes.MVC.Controllers
{
    public class StatisticsInsulinController : Controller
    {
        private readonly IMediator _mediator;

        public StatisticsInsulinController(IMediator mediator) => _mediator = mediator;

        [Authorize]
        public async Task<IActionResult> Index(string returnUrl)
        {
            var viewModel = new StatisticsInsulinViewModel
            {
                ReturnUrl = returnUrl,
            };

            Func<InsulinType, bool> IFilter = a => true;

            Func<DateTime, bool> DFilter = a => (DateTime.Now.Date - a.Date).Days < 7 && (DateTime.Now.Date - a.Date).Days >= 0;

            var command = new GetInsulinCommand
            {
                InsulinFilter = IFilter,
                DateFilter = DFilter
            };

            var itemsList = await _mediator.Send(command);
            itemsList = itemsList.Where(a => a.UserId == User.GetId()).ToList();

            viewModel.Categorical = itemsList.Select(a => a.MeasuringDateTime.ToString("dd.MM.yyyy HH:mm")).ToList();
            viewModel.Values = itemsList.Select(a => Math.Round(a.Value.Value, 2)).ToList();
            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> InsulinGraphics(StatisticsInsulinViewModel viewModel)
        {
            if (viewModel.CustomDate == null) viewModel.CustomDate = DateTime.Now.ToString("yyyy-MM-dd");
            Func<InsulinType, bool> IFilter = viewModel.InsulinAdditional switch
            {
                "1" => a => a == InsulinType.Short,
                "2" => a => a == InsulinType.Long,
                _ => a => true,
            };

            Func<DateTime, bool> DFilter = viewModel.InsulinTimePeriod switch
            {
                "1" => a => (DateTime.Now.Year - a.Year) * 12 +
                DateTime.Now.Month - a.Month +
                (DateTime.Now.Day >= a.Day ? 0 : -1) == 0,
                "2" => a => a.Date == DateTime.Now.Date,
                "3" => a => a.Date == DateTime.ParseExact(viewModel.CustomDate, "yyyy-MM-dd",
                CultureInfo.InvariantCulture).Date,
                "4" => a => true,
                _ => a => (DateTime.Now.Date - a.Date).Days < 7 && (DateTime.Now.Date - a.Date).Days >= 0,
            };

            var command = new GetInsulinCommand
            {
                InsulinFilter = IFilter,
                DateFilter = DFilter
            };

            var itemsList = await _mediator.Send(command);
            itemsList = itemsList.Where(a => a.UserId == User.GetId()).ToList();

            viewModel.Categorical = itemsList.Select(a => a.MeasuringDateTime.ToString("dd.MM.yyyy HH:mm")).ToList();
            viewModel.Values = itemsList.Select(a => Math.Round(a.Value.Value, 2)).ToList();
            return View(viewModel);
        }
    }
}

Diabetes.MVC/Views/StatisticsGlucose/GlucoseGraphics.cshtml
@using ShieldUI.AspNetCore.Mvc
@using Diabetes.Domain.Enums
@using Diabetes.Domain.Normalized.Enums.Units
@model Diabetes.MVC.Models.StatisticsGlucoseViewModel
@{
    ViewData["Title"] = "Статистика";
}

<div class="d-flex justify-content-around">
    <a class="btn active" asp-controller="StatisticsGlucose" asp-action="Index">Глюкоза</a>
    <a class="btn" asp-controller="StatisticsInsulin" asp-action="Index">Инсулин</a>
    <a class="btn" asp-controller="StatisticsCarbohydrates" asp-action="Index">Углеводы</a>
</div>

<div class="row mt-3"></div>

<div class="container mobile-container">
    <form asp-controller="StatisticsGlucose" asp-action="GlucoseGraphics" role="form" method="get">
        <select asp-for="GlucoseAdditional" asp-items="Html.GetEnumSelectList<MeasuringTimeTypeExtended>()" onchange="this.form.submit()"></select>
        <select asp-for="GlucoseTimePeriod" asp-items="Html.GetEnumSelectList<TimePeriods>()" onchange="this.form.submit()"></select>
        <select asp-for="GlucoseUnit" asp-items="Html.GetEnumSelectList<GlucoseUnits>()" onchange="this.form.submit()"></select>
        @if (Model.GlucoseTimePeriod == "3")
        {
            <script>
                var now = new Date()
                var day = ("0" + now.getDate()).slice(-2);
                var month = ("0" + (now.getMonth() + 1)).slice(-2);
                var date = now.getFullYear() + "-" + (month) + "-" + (day);
                $('#datePicker').val(date);
            </script>
            <div class="row mt-3"></div>
            <input asp-for="CustomDate" type="date" class="form-control" id="datePicker" min="0001-01-01" max="9999-12-31" onfocusout="this.form.submit()">
        }
    </form>
    <div class="row mt-3"></div>
    @(Html.ShieldChart(Model.GetData())
    .Name("chart")
   .Tooltip(tooltip => tooltip.AxisMarkers(axisMarkers => axisMarkers
        .Enabled(true)
        .Mode(ShieldUI.AspNetCore.Mvc.Chart.TooltipAxisMarkerMode.XY)
        .Width(1)
        .ZIndex(3)))
    .Theme("light")
    .PrimaryHeader(header => header.Text("Изменение уровня глюкозы"))
    .Export(false)
    .AxisX(axisX => axisX.CategoricalValues(model => model.Categorical))
    .AxisX(axisX => axisX.Title(title => title.Text("Время")))
    .AxisX(axisX => axisX.AxisTickText(axisTickText => axisTickText.Enabled(false)))
    .AxisY(axisY => axisY.Title(title => title.Text("Значение")))
    .DataSeries(series =>
    series.Spline()
        .Name("Реальный уровень глюкозы")
        .Color("CornflowerBlue")
        .Data(model => model.Value))
    .DataSeries(series =>
      series.Spline()
        .Name("Нормальный уровень глюкозы до еды")
        .SeriesDashStyle(ShieldUI.AspNetCore.Mvc.Chart.DashType.Dash)
        .Color("Gold")
        .Visible(Model.GlucoseAdditional != "2" && Model.HasNormalBeforeEating)
        .Data(model => model.NormalValueBeforeEating))
    .DataSeries(series =>
    series.Spline()
        .Name("Нормальный уровень глюкозы после еды")
        .SeriesDashStyle(ShieldUI.AspNetCore.Mvc.Chart.DashType.Dash)
        .Color("Coral")
        .Visible(Model.GlucoseAdditional != "1" && Model.HasNormalAfterEating)
        .Data(model => model.NormalValueAfterEating)))

    <div class="row mt-3"></div>
    <div class="mb-3">
        <div><font size="4">Минимальное значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Min(), 2).ToString())</font></div>
        <div><font size="4">Среднее значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Average(), 2).ToString())</font></div>
        <div><font size="4">Максимальное значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Max(), 2).ToString())</font></div>
    </div>
</div>

<div class="row mt-3"></div>

Diabetes.MVC/Views/StatisticsGlucose/Index.cshtml
@using ShieldUI.AspNetCore.Mvc
@using Diabetes.Domain.Enums
@using Diabetes.Domain.Normalized.Enums.Units 
@model Diabetes.MVC.Models.StatisticsGlucoseViewModel
@{
    ViewData["Title"] = "Статистика";
}

<div class="d-flex justify-content-around">
    <a class="btn active" asp-controller="StatisticsGlucose" asp-action="Index">Глюкоза</a>
    <a class="btn" asp-controller="StatisticsInsulin" asp-action="Index">Инсулин</a>
    <a class="btn" asp-controller="StatisticsCarbohydrates" asp-action="Index">Углеводы</a>
</div>

<div class="row mt-3"></div>

<div class="container mobile-container">
    <form asp-controller="StatisticsGlucose" asp-action="GlucoseGraphics" role="form" method="get">
        <select asp-for="GlucoseAdditional" asp-items="Html.GetEnumSelectList<MeasuringTimeTypeExtended>()" onchange="this.form.submit()"></select>
        <select asp-for="GlucoseTimePeriod" asp-items="Html.GetEnumSelectList<TimePeriods>()" onchange="this.form.submit()"></select>
        <select asp-for="GlucoseUnit" asp-items="Html.GetEnumSelectList<GlucoseUnits>()" onchange="this.form.submit()"></select>
        @if (Model.GlucoseTimePeriod == "3")
        {
            <div class="row mt-3"></div>
            <input asp-for="CustomDate" type="date" class="form-control" id="datePicker" min="0001-01-01" max="9999-12-31" onfocusout="this.form.submit()">
        }
    </form>
    <div class="row mt-3"></div>
    @(Html.ShieldChart(Model.GetData())
    .Name("chart")
   .Tooltip(tooltip => tooltip.AxisMarkers(axisMarkers => axisMarkers
        .Enabled(true)
        .Mode(ShieldUI.AspNetCore.Mvc.Chart.TooltipAxisMarkerMode.XY)
        .Width(1)
        .ZIndex(3)))
    .Theme("light")
    .PrimaryHeader(header => header.Text("Изменение уровня глюкозы"))
    .Export(false)
    .AxisX(axisX => axisX.CategoricalValues(model => model.Categorical))
    .AxisX(axisX => axisX.Title(title => title.Text("Время")))
    .AxisX(axisX => axisX.AxisTickText(axisTickText => axisTickText.Enabled(false)))
    .AxisY(axisY => axisY.Title(title => title.Text("Значение")))
    .DataSeries(series =>
    series.Spline()
        .Name("Реальный уровень глюкозы")
        .Color("CornflowerBlue")
        .Data(model => model.Value))
    .DataSeries(series =>
    series.Spline()
        .Name("Нормальный уровень глюкозы до еды")
        .SeriesDashStyle(ShieldUI.AspNetCore.Mvc.Chart.DashType.Dash)
        .Color("Gold")
        .Visible(Model.GlucoseAdditional != "2" && Model.HasNormalBeforeEating)
        .Data(model => model.NormalValueBeforeEating))
    .DataSeries(series =>
    series.Spline()
        .Name("Нормальный уровень глюкозы после еды")
        .SeriesDashStyle(ShieldUI.AspNetCore.Mvc.Chart.DashType.Dash)
        .Color("Coral")
        .Visible(Model.GlucoseAdditional != "1" && Model.HasNormalAfterEating)
        .Data(model => model.NormalValueAfterEating)))

    <div class="row mt-3"></div>
    <div class="mb-3">
        <div><font size="4">Минимальное значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Min(), 2).ToString())</font></div>
        <div><font size="4">Среднее значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Average(), 2).ToString())</font></div>
        <div><font size="4">Максимальное значение: @(Model.Values.Count == 0 ? "неизвестно" : Math.Round(Model.Values.Max(), 2).ToString())</font></div>
    </div>
</div>

<div class="row mt-3"></div>